features:
  - A_bbWW_mT
  - A_bbWW_vis_dR
  - A_bbWW_vis_m
  - A_WW_mT
  - A_WW_vis_dR
  - A_WW_vis_m
  - A_Whad_dR
  - A_Whad_m
  - A_Whad_pt
  - A_min_dR_l_q
  - A_q1_pt
  - A_q1_eta
  - A_q2_pt
  - A_q2_eta
  - B_bbWW_mT
  - B_bbWW_vis_dR
  - B_bbWW_vis_m
  - B_WW_mT
  - B_WW_vis_dR
  - B_WW_vis_m
  - B_Whad_dR
  - B_Whad_m
  - B_Whad_pt
  - B_min_dR_l_q
  - B_q1_pt
  - B_q1_eta
  - B_q2_pt
  - B_q2_eta
  - b1_pt
  - b1_eta
  - b2_pt
  - b2_eta
  - met_pt
  - lep_pt
  - lep_eta
  - W_mT
  - bb_inv
  - bb_dr
  - n_b_jets
  - topness
  - top_dr_lb
  - top_m_lb
  - top_tlep_reco_mass
  - top_whad_reco_mass
  - top_whad_dr_qq
  - top_thad_reco_mass
  - top_thad_dr_bqq


